### ISSUE TITLE
runtime error after create a VM instance without external IP address

### ISSUE THREAD

**Issue by minimum2scp** [minimum2scp/geco#25]
After create a VM instance `nat-test-1` with no external IP address and `geco cache`,

```console
tsuyoshi@wezen% gcloud compute instances list 
NAME        ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP   STATUS
bastion-1   us-central1-c  n1-standard-1               192.168.1.2  x.x.x.x       RUNNING
nat-test-1  us-central1-c  n1-standard-1               192.168.1.3                RUNNING
tsuyoshi@wezen% geco cache
2019/01/11 15:48:03 loading projects...
2019/01/11 15:48:04 loaded projects, 5 projects found.
(...snip...)
2019/01/11 15:48:05 saved cache.
```

`geco ssh` failed with `panic: runtime error: index out of range`.

```console
tsuyoshi@wezen% geco ssh
panic: runtime error: index out of range

goroutine 1 [running]:
main.renderInstanceTable(0xc4201a0e40, 0x11, 0xc4201dcca0, 0x2, 0x4, 0x10, 0x2, 0x1)
	/home/travis/gopath/src/github.com/minimum2scp/geco/commands.go:393 +0x646
main.doSSH(0xc4201e23c0)
	/home/travis/gopath/src/github.com/minimum2scp/geco/commands.go:311 +0xfd
github.com/minimum2scp/geco/vendor/github.com/codegangsta/cli.HandleAction(0x945520, 0xa80038, 0xc4201e23c0, 0xc4201e6300, 0x0)
	/home/travis/gopath/src/github.com/minimum2scp/geco/vendor/github.com/codegangsta/cli/app.go:487 +0x7c
github.com/minimum2scp/geco/vendor/github.com/codegangsta/cli.Command.Run(0xa5d927, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/minimum2scp/geco/vendor/github.com/codegangsta/cli/command.go:193 +0xa99
github.com/minimum2scp/geco/vendor/github.com/codegangsta/cli.(*App).Run(0xc4201f81a0, 0xc420080020, 0x2, 0x2, 0x0, 0x0)
	/home/travis/gopath/src/github.com/minimum2scp/geco/vendor/github.com/codegangsta/cli/app.go:250 +0x758
main.main()
	/home/travis/gopath/src/github.com/minimum2scp/geco/geco.go:20 +0x175
```

commands.go:393 

https://github.com/minimum2scp/geco/blob/cb65a16d969177cfc7854d0c6f1227f0b58a3197/commands.go#L393

**Comment by minimum2scp** [comment]
```console
tsuyoshi@wezen% jq '.[]|{name, networkInterfaces}' ~/.cache/geco/instances.json
{
  "name": "bastion-1",
  "networkInterfaces": [
    {
      "accessConfigs": [
        {
          "kind": "compute#accessConfig",
          "name": "external-nat",
          "natIP": "x.x.x.x",
          "type": "ONE_TO_ONE_NAT"
        }
      ],
      "name": "nic0",
      "network": "https://www.googleapis.com/compute/v1/projects/gae-test-20170530/global/networks/custom-network1",
      "networkIP": "192.168.1.2",
      "subnetwork": "https://www.googleapis.com/compute/v1/projects/gae-test-20170530/regions/us-central1/subnetworks/subnet-us-central-192"
    }
  ]
}
{
  "name": "nat-test-1",
  "networkInterfaces": [
    {
      "name": "nic0",
      "network": "https://www.googleapis.com/compute/v1/projects/gae-test-20170530/global/networks/custom-network1",
      "networkIP": "192.168.1.3",
      "subnetwork": "https://www.googleapis.com/compute/v1/projects/gae-test-20170530/regions/us-central1/subnetworks/subnet-us-central-192"
    }
  ]
}
```

**Comment by minimum2scp** [comment]
```console
tsuyoshi@wezen% jq '.[]|{name, networkInterfaces}' ~/.cache/geco/instances.json
{
  "name": "bastion-1",
  "networkInterfaces": [
    {
      "accessConfigs": [
        {
          "kind": "compute#accessConfig",
          "name": "external-nat",
          "natIP": "x.x.x.x",
          "type": "ONE_TO_ONE_NAT"
        }
      ],
      "name": "nic0",
      "network": "https://www.googleapis.com/compute/v1/projects/******/global/networks/custom-network1",
      "networkIP": "192.168.1.2",
      "subnetwork": "https://www.googleapis.com/compute/v1/projects/******/regions/us-central1/subnetworks/subnet-us-central-192"
    }
  ]
}
{
  "name": "nat-test-1",
  "networkInterfaces": [
    {
      "name": "nic0",
      "network": "https://www.googleapis.com/compute/v1/projects/******/global/networks/custom-network1",
      "networkIP": "192.168.1.3",
      "subnetwork": "https://www.googleapis.com/compute/v1/projects/******/regions/us-central1/subnetworks/subnet-us-central-192"
    }
  ]
}
```
